_extends: nestjs-monorepo-release-drafter-sample:.github/release-drafter-base-config.yml # 継承元の設定ファイルをリポジトリ名:ファイルパスで指定
name-template: shared@$RESOLVED_VERSION # リリースノートのタイトルはタグ名と同じにする
tag-template: shared@$RESOLVED_VERSION # タイトルとタグ名を同じにする
tag-prefix: shared@ # tagのprefixを指定
include-paths: # sharedのリリースノートに含めるファイルパスを指定
  - "libs/shared/"
