_extends: nestjs-monorepo-release-drafter-sample:.github/release-drafter-base-config.yml # 継承元の設定ファイルをリポジトリ名:ファイルパスで指定
name-template: products-api@$RESOLVED_VERSION # リリースノートのタイトルはタグ名と同じにする
tag-template: products-api@$RESOLVED_VERSION # タイトルとタグ名を同じにする
tag-prefix: products-api@ # tagのprefixを指定
include-paths: # products-apiのリリースノートに含めるファイルパスを指定
  - "apps/products-api/"
