name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft products-api release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-products-api.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft users-api release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-users-api.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft shared library release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-shared.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
